/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApikeysView {
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "lastUsedAt", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// \"sk_live_aB3x\" (first 12 chars), safe to display
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "revokedAt", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<String>,
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
}

impl ApikeysView {
    pub fn new() -> ApikeysView {
        ApikeysView {
            created_at: None,
            id: None,
            last_used_at: None,
            name: None,
            prefix: None,
            revoked_at: None,
            tenant_id: None,
        }
    }
}
