/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimInvitationRegisterCustomerResponse {
    /// Created is false when the billing service already knew the address, so a re-run of an import reports what it actually added rather than what it sent.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<bool>,
}

impl ClaimInvitationRegisterCustomerResponse {
    pub fn new() -> ClaimInvitationRegisterCustomerResponse {
        ClaimInvitationRegisterCustomerResponse {
            created: None,
        }
    }
}
