/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUsageUsageResponse {
    #[serde(rename = "currentPeriod", skip_serializing_if = "Option::is_none")]
    pub current_period: Option<Box<models::GetUsageCurrentPeriodView>>,
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Vec<models::GetUsageHistoryEntry>>,
}

impl GetUsageUsageResponse {
    pub fn new() -> GetUsageUsageResponse {
        GetUsageUsageResponse {
            current_period: None,
            history: None,
        }
    }
}
