/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUsageCurrentPeriodView {
    #[serde(rename = "byIdentity", skip_serializing_if = "Option::is_none")]
    pub by_identity: Option<Vec<models::GetUsageIdentityBreakdown>>,
    /// IncludedEmails is what the subscription price buys. On a plan with no hard cap it is the only number that tells a tenant where billing starts, since Limit is -1 there.
    #[serde(rename = "includedEmails", skip_serializing_if = "Option::is_none")]
    pub included_emails: Option<i32>,
    /// -1 means unlimited
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "overageCents", skip_serializing_if = "Option::is_none")]
    pub overage_cents: Option<i32>,
    /// OverageEmails is how much of SentCount sits past IncludedEmails, and OverageCents what it would cost. Reported, not yet invoiced — see the note on Pro in plans/domain/catalog.go.
    #[serde(rename = "overageEmails", skip_serializing_if = "Option::is_none")]
    pub overage_emails: Option<i32>,
    #[serde(rename = "periodStart", skip_serializing_if = "Option::is_none")]
    pub period_start: Option<String>,
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<String>,
    #[serde(rename = "sentCount", skip_serializing_if = "Option::is_none")]
    pub sent_count: Option<i32>,
}

impl GetUsageCurrentPeriodView {
    pub fn new() -> GetUsageCurrentPeriodView {
        GetUsageCurrentPeriodView {
            by_identity: None,
            included_emails: None,
            limit: None,
            overage_cents: None,
            overage_emails: None,
            period_start: None,
            plan: None,
            sent_count: None,
        }
    }
}
