/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCatalogueCatalogue {
    /// Degraded reports that Lungor could not be reached and nothing here can be bought.
    #[serde(rename = "degraded", skip_serializing_if = "Option::is_none")]
    pub degraded: Option<bool>,
    #[serde(rename = "plans", skip_serializing_if = "Option::is_none")]
    pub plans: Option<Vec<models::GetCataloguePlan>>,
}

impl GetCatalogueCatalogue {
    pub fn new() -> GetCatalogueCatalogue {
        GetCatalogueCatalogue {
            degraded: None,
            plans: None,
        }
    }
}
