/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngestBounceResponse {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "permanent", skip_serializing_if = "Option::is_none")]
    pub permanent: Option<bool>,
    #[serde(rename = "recipient", skip_serializing_if = "Option::is_none")]
    pub recipient: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "suppression", skip_serializing_if = "Option::is_none")]
    pub suppression: Option<Box<models::AddSuppressionResponse>>,
}

impl IngestBounceResponse {
    pub fn new() -> IngestBounceResponse {
        IngestBounceResponse {
            action: None,
            permanent: None,
            recipient: None,
            status: None,
            suppression: None,
        }
    }
}
