/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListIdentitiesResponse {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::RepositoryIdentityView>>,
}

impl ListIdentitiesResponse {
    pub fn new() -> ListIdentitiesResponse {
        ListIdentitiesResponse {
            items: None,
        }
    }
}
