/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCheckoutMethodsMethod {
    /// ID travels back as the checkout's paymentMethod.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Label names the method for the buyer.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl ListCheckoutMethodsMethod {
    pub fn new() -> ListCheckoutMethodsMethod {
        ListCheckoutMethodsMethod {
            id: None,
            label: None,
        }
    }
}
