/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListInboundMessagesResponse {
    #[serde(rename = "messages", skip_serializing_if = "Option::is_none")]
    pub messages: Option<Vec<models::RepositoryInboundMessageView>>,
}

impl ListInboundMessagesResponse {
    pub fn new() -> ListInboundMessagesResponse {
        ListInboundMessagesResponse {
            messages: None,
        }
    }
}
