/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryAttemptView {
    #[serde(rename = "attemptNum", skip_serializing_if = "Option::is_none")]
    pub attempt_num: Option<i32>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "mtaResponse", skip_serializing_if = "Option::is_none")]
    pub mta_response: Option<String>,
    #[serde(rename = "occurredAt", skip_serializing_if = "Option::is_none")]
    pub occurred_at: Option<String>,
    #[serde(rename = "outcome", skip_serializing_if = "Option::is_none")]
    pub outcome: Option<String>,
}

impl RepositoryAttemptView {
    pub fn new() -> RepositoryAttemptView {
        RepositoryAttemptView {
            attempt_num: None,
            error: None,
            mta_response: None,
            occurred_at: None,
            outcome: None,
        }
    }
}
