/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnfreezeResponse {
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    #[serde(rename = "unfrozenAt", skip_serializing_if = "Option::is_none")]
    pub unfrozen_at: Option<String>,
}

impl UnfreezeResponse {
    pub fn new() -> UnfreezeResponse {
        UnfreezeResponse {
            reason: None,
            state: None,
            tenant_id: None,
            unfrozen_at: None,
        }
    }
}
