packages:
  - "skalpai/*"
  - "spore/*"
  - "lalter/*"
  - "lungor/*"
  - "auth"
  - "keys"
  - "legal"
  - "admin"
  - "editor"
allowBuilds:
  '@openapitools/openapi-generator-cli': true
  '@scarf/scarf': false
  esbuild: true
  protobufjs: false
