# -*- encoding: utf-8 -*-

=begin
#Spore API

#Control plane for the Spore transactional email platform.

The version of the OpenAPI document: 0.1.0
Contact: contact@sporee.fr
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "spore-email/version"

Gem::Specification.new do |s|
  s.name        = "spore-email"
  s.version     = SporeEmail::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Spore"]
  s.email       = ["contact@sporee.fr"]
  s.homepage    = "https://sporee.fr/docs/sdks/ruby"
  s.summary     = "Typed Ruby client for the Spore transactional email API"
  s.description = "Send DKIM-signed transactional email through Spore from Ruby and Rails."
  s.license     = "Nonstandard"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
