"""
    Spore API

    Control plane for the Spore transactional email platform.

    The version of the OpenAPI document: 0.1.0
    Contact: contact@sporee.fr
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "spore-email"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">= 3.10"
REQUIRES = [
    "urllib3 >= 2.6.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Spore API",
    author="Spore",
    author_email="contact@sporee.fr",
    url="https://github.com/lalternativefabrique/packages/tree/main/spore/sdk-python",
    keywords=["OpenAPI", "OpenAPI-Generator", "Spore API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Proprietary",
    long_description_content_type='text/markdown',
    long_description="""\
    Control plane for the Spore transactional email platform.
    """,  # noqa: E501
    package_data={"spore_email": ["py.typed"]},
)
