// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package wire

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// ChatAttachmentDTO defines model for chat.AttachmentDTO.
type ChatAttachmentDTO struct {
	Filename  *string `json:"filename,omitempty"`
	Id        *string `json:"id,omitempty"`
	MimeType  *string `json:"mime_type,omitempty"`
	SizeBytes *int    `json:"size_bytes,omitempty"`
}

// ChatConversationDTO defines model for chat.ConversationDTO.
type ChatConversationDTO struct {
	BaseRef   *string `json:"base_ref,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	HasRepo   *bool   `json:"has_repo,omitempty"`
	Id        *string `json:"id,omitempty"`
	Title     *string `json:"title,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// ChatErrorResponse defines model for chat.ErrorResponse.
type ChatErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// ChatMessageDTO defines model for chat.MessageDTO.
type ChatMessageDTO struct {
	At          *string              `json:"at,omitempty"`
	Attachments *[]ChatAttachmentDTO `json:"attachments,omitempty"`
	Content     *string              `json:"content,omitempty"`
	Id          *string              `json:"id,omitempty"`
	Role        *string              `json:"role,omitempty"`
	ToolArgs    *string              `json:"tool_args,omitempty"`
	ToolMeta    *string              `json:"tool_meta,omitempty"`
	ToolName    *string              `json:"tool_name,omitempty"`
	Vote        *int                 `json:"vote,omitempty"`
}

// ChatSendRequest defines model for chat.SendRequest.
type ChatSendRequest struct {
	// AttachmentIds AttachmentIDs names files uploaded ahead of this turn via
	// POST /chat/attachments. Each must belong to the caller and, once the
	// conversation exists, to this thread.
	AttachmentIds  *[]string `json:"attachment_ids,omitempty"`
	BaseRef        *string   `json:"base_ref,omitempty"`
	ConversationId *string   `json:"conversation_id,omitempty"`
	Message        *string   `json:"message,omitempty"`

	// RepoUrl RepoURL points a new conversation at a repository, credentials
	// included. Ignored once the thread exists — a thread works on one
	// repository, and moving it mid-way would make its own history lie.
	RepoUrl *string `json:"repo_url,omitempty"`

	// Timezone Timezone is the caller's IANA zone (e.g. "Europe/Paris"), used to speak
	// times in the person's own clock instead of UTC. Empty falls back to UTC.
	Timezone *string `json:"timezone,omitempty"`
}

// ChatVoteRequest defines model for chat.VoteRequest.
type ChatVoteRequest struct {
	// Vote Vote is 1 (up), -1 (down), or 0 to clear a previous vote.
	Vote *int `json:"vote,omitempty"`
}

// TaskCreateTaskRequest defines model for task.CreateTaskRequest.
type TaskCreateTaskRequest struct {
	BaseRef *string `json:"base_ref,omitempty"`

	// McpServers MCPServers names MCP servers this run may use, by name — never a
	// command. Each name must already be registered on this deployment
	// (LALTER_MCP_SERVERS); an unrecognized name refuses the whole request
	// with 400 rather than silently running with fewer tools than asked for.
	McpServers *[]string `json:"mcp_servers,omitempty"`
	Prompt     *string   `json:"prompt,omitempty"`
	RepoUrl    *string   `json:"repo_url,omitempty"`

	// ReportDiff ReportDiff asks the run to read back and return the working tree diff
	// once the agent finishes. A caller giving the agent no write tools has
	// nothing to read back.
	ReportDiff *bool `json:"report_diff,omitempty"`

	// SystemPrompt SystemPrompt is passed to the agent verbatim.
	SystemPrompt *string `json:"system_prompt,omitempty"`

	// Tools Tools names the local tools the agent may use: read, grep, glob, edit,
	// write, bash. An unrecognized name is silently skipped, not refused.
	Tools *[]string `json:"tools,omitempty"`
}

// TaskErrorResponse defines model for task.ErrorResponse.
type TaskErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// TaskStepDTO defines model for task.StepDTO.
type TaskStepDTO struct {
	Arguments  *string `json:"arguments,omitempty"`
	At         *string `json:"at,omitempty"`
	DurationMs *int    `json:"duration_ms,omitempty"`
	Error      *string `json:"error,omitempty"`
	Result     *string `json:"result,omitempty"`
	Seq        *int    `json:"seq,omitempty"`
	Tool       *string `json:"tool,omitempty"`
}

// TaskTaskDTO defines model for task.TaskDTO.
type TaskTaskDTO struct {
	BaseRef      *string       `json:"base_ref,omitempty"`
	CreatedAt    *string       `json:"created_at,omitempty"`
	Diff         *string       `json:"diff,omitempty"`
	Error        *string       `json:"error,omitempty"`
	Id           *string       `json:"id,omitempty"`
	McpServers   *[]string     `json:"mcp_servers,omitempty"`
	Model        *string       `json:"model,omitempty"`
	Prompt       *string       `json:"prompt,omitempty"`
	ReportDiff   *bool         `json:"report_diff,omitempty"`
	SettledAt    *string       `json:"settled_at,omitempty"`
	StartedAt    *string       `json:"started_at,omitempty"`
	Status       *string       `json:"status,omitempty"`
	Summary      *string       `json:"summary,omitempty"`
	SystemPrompt *string       `json:"system_prompt,omitempty"`
	Tools        *[]string     `json:"tools,omitempty"`
	Usage        *TaskUsageDTO `json:"usage,omitempty"`
}

// TaskUsageDTO defines model for task.UsageDTO.
type TaskUsageDTO struct {
	CachedInputTokens *int `json:"cached_input_tokens,omitempty"`
	InputTokens       *int `json:"input_tokens,omitempty"`
	OutputTokens      *int `json:"output_tokens,omitempty"`
	Steps             *int `json:"steps,omitempty"`
}

// UploadChatAttachmentMultipartBody defines parameters for UploadChatAttachment.
type UploadChatAttachmentMultipartBody struct {
	// ConversationId Conversation the file belongs to
	ConversationId string `json:"conversation_id"`

	// File The file
	File openapi_types.File `json:"file"`
}

// GetMessageAudioParams defines parameters for GetMessageAudio.
type GetMessageAudioParams struct {
	// Stream 1 streams the reading piece by piece
	Stream *string `form:"stream,omitempty" json:"stream,omitempty"`
}

// UploadChatAttachmentMultipartRequestBody defines body for UploadChatAttachment for multipart/form-data ContentType.
type UploadChatAttachmentMultipartRequestBody UploadChatAttachmentMultipartBody

// VoteChatMessageJSONRequestBody defines body for VoteChatMessage for application/json ContentType.
type VoteChatMessageJSONRequestBody = ChatVoteRequest

// SendChatMessageJSONRequestBody defines body for SendChatMessage for application/json ContentType.
type SendChatMessageJSONRequestBody = ChatSendRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = TaskCreateTaskRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// UploadChatAttachmentWithBody request with any body
	UploadChatAttachmentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetChatAttachment request
	GetChatAttachment(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListConversations request
	ListConversations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteConversation request
	DeleteConversation(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConversationMessages request
	GetConversationMessages(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMessageAudio request
	GetMessageAudio(ctx context.Context, id string, messageId string, params *GetMessageAudioParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VoteChatMessageWithBody request with any body
	VoteChatMessageWithBody(ctx context.Context, id string, messageId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	VoteChatMessage(ctx context.Context, id string, messageId string, body VoteChatMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendChatMessageWithBody request with any body
	SendChatMessageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SendChatMessage(ctx context.Context, body SendChatMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListTasks request
	ListTasks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateTaskWithBody request with any body
	CreateTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateTask(ctx context.Context, body CreateTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTask request
	GetTask(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTaskSteps request
	GetTaskSteps(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) UploadChatAttachmentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadChatAttachmentRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetChatAttachment(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChatAttachmentRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListConversations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListConversationsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteConversation(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteConversationRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConversationMessages(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConversationMessagesRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMessageAudio(ctx context.Context, id string, messageId string, params *GetMessageAudioParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMessageAudioRequest(c.Server, id, messageId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VoteChatMessageWithBody(ctx context.Context, id string, messageId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVoteChatMessageRequestWithBody(c.Server, id, messageId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VoteChatMessage(ctx context.Context, id string, messageId string, body VoteChatMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVoteChatMessageRequest(c.Server, id, messageId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendChatMessageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendChatMessageRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendChatMessage(ctx context.Context, body SendChatMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendChatMessageRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListTasks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTasksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateTaskWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTaskRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateTask(ctx context.Context, body CreateTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTaskRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTask(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTaskRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTaskSteps(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTaskStepsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewUploadChatAttachmentRequestWithBody generates requests for UploadChatAttachment with any type of body
func NewUploadChatAttachmentRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/chat/attachments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetChatAttachmentRequest generates requests for GetChatAttachment
func NewGetChatAttachmentRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/chat/attachments/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListConversationsRequest generates requests for ListConversations
func NewListConversationsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/chat/conversations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteConversationRequest generates requests for DeleteConversation
func NewDeleteConversationRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/chat/conversations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetConversationMessagesRequest generates requests for GetConversationMessages
func NewGetConversationMessagesRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/chat/conversations/%s/messages", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMessageAudioRequest generates requests for GetMessageAudio
func NewGetMessageAudioRequest(server string, id string, messageId string, params *GetMessageAudioParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "messageId", runtime.ParamLocationPath, messageId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/chat/conversations/%s/messages/%s/audio", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Stream != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "stream", runtime.ParamLocationQuery, *params.Stream); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewVoteChatMessageRequest calls the generic VoteChatMessage builder with application/json body
func NewVoteChatMessageRequest(server string, id string, messageId string, body VoteChatMessageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewVoteChatMessageRequestWithBody(server, id, messageId, "application/json", bodyReader)
}

// NewVoteChatMessageRequestWithBody generates requests for VoteChatMessage with any type of body
func NewVoteChatMessageRequestWithBody(server string, id string, messageId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "messageId", runtime.ParamLocationPath, messageId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/chat/conversations/%s/messages/%s/vote", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSendChatMessageRequest calls the generic SendChatMessage builder with application/json body
func NewSendChatMessageRequest(server string, body SendChatMessageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendChatMessageRequestWithBody(server, "application/json", bodyReader)
}

// NewSendChatMessageRequestWithBody generates requests for SendChatMessage with any type of body
func NewSendChatMessageRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/chat/send")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListTasksRequest generates requests for ListTasks
func NewListTasksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tasks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateTaskRequest calls the generic CreateTask builder with application/json body
func NewCreateTaskRequest(server string, body CreateTaskJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateTaskRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateTaskRequestWithBody generates requests for CreateTask with any type of body
func NewCreateTaskRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tasks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTaskRequest generates requests for GetTask
func NewGetTaskRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tasks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTaskStepsRequest generates requests for GetTaskSteps
func NewGetTaskStepsRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tasks/%s/steps", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// UploadChatAttachmentWithBodyWithResponse request with any body
	UploadChatAttachmentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadChatAttachmentResponse, error)

	// GetChatAttachmentWithResponse request
	GetChatAttachmentWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetChatAttachmentResponse, error)

	// ListConversationsWithResponse request
	ListConversationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListConversationsResponse, error)

	// DeleteConversationWithResponse request
	DeleteConversationWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteConversationResponse, error)

	// GetConversationMessagesWithResponse request
	GetConversationMessagesWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetConversationMessagesResponse, error)

	// GetMessageAudioWithResponse request
	GetMessageAudioWithResponse(ctx context.Context, id string, messageId string, params *GetMessageAudioParams, reqEditors ...RequestEditorFn) (*GetMessageAudioResponse, error)

	// VoteChatMessageWithBodyWithResponse request with any body
	VoteChatMessageWithBodyWithResponse(ctx context.Context, id string, messageId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VoteChatMessageResponse, error)

	VoteChatMessageWithResponse(ctx context.Context, id string, messageId string, body VoteChatMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*VoteChatMessageResponse, error)

	// SendChatMessageWithBodyWithResponse request with any body
	SendChatMessageWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendChatMessageResponse, error)

	SendChatMessageWithResponse(ctx context.Context, body SendChatMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*SendChatMessageResponse, error)

	// ListTasksWithResponse request
	ListTasksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListTasksResponse, error)

	// CreateTaskWithBodyWithResponse request with any body
	CreateTaskWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTaskResponse, error)

	CreateTaskWithResponse(ctx context.Context, body CreateTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTaskResponse, error)

	// GetTaskWithResponse request
	GetTaskWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetTaskResponse, error)

	// GetTaskStepsWithResponse request
	GetTaskStepsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetTaskStepsResponse, error)
}

type UploadChatAttachmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChatAttachmentDTO
	JSON400      *ChatErrorResponse
	JSON404      *ChatErrorResponse
}

// Status returns HTTPResponse.Status
func (r UploadChatAttachmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadChatAttachmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetChatAttachmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetChatAttachmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChatAttachmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListConversationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ChatConversationDTO
}

// Status returns HTTPResponse.Status
func (r ListConversationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListConversationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteConversationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteConversationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteConversationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetConversationMessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ChatMessageDTO
	JSON404      *ChatErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetConversationMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConversationMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMessageAudioResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetMessageAudioResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMessageAudioResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VoteChatMessageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ChatErrorResponse
	JSON404      *ChatErrorResponse
}

// Status returns HTTPResponse.Status
func (r VoteChatMessageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VoteChatMessageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SendChatMessageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r SendChatMessageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendChatMessageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListTasksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TaskTaskDTO
}

// Status returns HTTPResponse.Status
func (r ListTasksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTasksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateTaskResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *TaskTaskDTO
	JSON400      *TaskErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateTaskResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateTaskResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTaskResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TaskTaskDTO
	JSON404      *TaskErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetTaskResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTaskResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTaskStepsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TaskStepDTO
}

// Status returns HTTPResponse.Status
func (r GetTaskStepsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTaskStepsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// UploadChatAttachmentWithBodyWithResponse request with arbitrary body returning *UploadChatAttachmentResponse
func (c *ClientWithResponses) UploadChatAttachmentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadChatAttachmentResponse, error) {
	rsp, err := c.UploadChatAttachmentWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadChatAttachmentResponse(rsp)
}

// GetChatAttachmentWithResponse request returning *GetChatAttachmentResponse
func (c *ClientWithResponses) GetChatAttachmentWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetChatAttachmentResponse, error) {
	rsp, err := c.GetChatAttachment(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChatAttachmentResponse(rsp)
}

// ListConversationsWithResponse request returning *ListConversationsResponse
func (c *ClientWithResponses) ListConversationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListConversationsResponse, error) {
	rsp, err := c.ListConversations(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListConversationsResponse(rsp)
}

// DeleteConversationWithResponse request returning *DeleteConversationResponse
func (c *ClientWithResponses) DeleteConversationWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteConversationResponse, error) {
	rsp, err := c.DeleteConversation(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteConversationResponse(rsp)
}

// GetConversationMessagesWithResponse request returning *GetConversationMessagesResponse
func (c *ClientWithResponses) GetConversationMessagesWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetConversationMessagesResponse, error) {
	rsp, err := c.GetConversationMessages(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConversationMessagesResponse(rsp)
}

// GetMessageAudioWithResponse request returning *GetMessageAudioResponse
func (c *ClientWithResponses) GetMessageAudioWithResponse(ctx context.Context, id string, messageId string, params *GetMessageAudioParams, reqEditors ...RequestEditorFn) (*GetMessageAudioResponse, error) {
	rsp, err := c.GetMessageAudio(ctx, id, messageId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMessageAudioResponse(rsp)
}

// VoteChatMessageWithBodyWithResponse request with arbitrary body returning *VoteChatMessageResponse
func (c *ClientWithResponses) VoteChatMessageWithBodyWithResponse(ctx context.Context, id string, messageId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VoteChatMessageResponse, error) {
	rsp, err := c.VoteChatMessageWithBody(ctx, id, messageId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVoteChatMessageResponse(rsp)
}

func (c *ClientWithResponses) VoteChatMessageWithResponse(ctx context.Context, id string, messageId string, body VoteChatMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*VoteChatMessageResponse, error) {
	rsp, err := c.VoteChatMessage(ctx, id, messageId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVoteChatMessageResponse(rsp)
}

// SendChatMessageWithBodyWithResponse request with arbitrary body returning *SendChatMessageResponse
func (c *ClientWithResponses) SendChatMessageWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendChatMessageResponse, error) {
	rsp, err := c.SendChatMessageWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendChatMessageResponse(rsp)
}

func (c *ClientWithResponses) SendChatMessageWithResponse(ctx context.Context, body SendChatMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*SendChatMessageResponse, error) {
	rsp, err := c.SendChatMessage(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendChatMessageResponse(rsp)
}

// ListTasksWithResponse request returning *ListTasksResponse
func (c *ClientWithResponses) ListTasksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListTasksResponse, error) {
	rsp, err := c.ListTasks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTasksResponse(rsp)
}

// CreateTaskWithBodyWithResponse request with arbitrary body returning *CreateTaskResponse
func (c *ClientWithResponses) CreateTaskWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTaskResponse, error) {
	rsp, err := c.CreateTaskWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTaskResponse(rsp)
}

func (c *ClientWithResponses) CreateTaskWithResponse(ctx context.Context, body CreateTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTaskResponse, error) {
	rsp, err := c.CreateTask(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTaskResponse(rsp)
}

// GetTaskWithResponse request returning *GetTaskResponse
func (c *ClientWithResponses) GetTaskWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetTaskResponse, error) {
	rsp, err := c.GetTask(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTaskResponse(rsp)
}

// GetTaskStepsWithResponse request returning *GetTaskStepsResponse
func (c *ClientWithResponses) GetTaskStepsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetTaskStepsResponse, error) {
	rsp, err := c.GetTaskSteps(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTaskStepsResponse(rsp)
}

// ParseUploadChatAttachmentResponse parses an HTTP response from a UploadChatAttachmentWithResponse call
func ParseUploadChatAttachmentResponse(rsp *http.Response) (*UploadChatAttachmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadChatAttachmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChatAttachmentDTO
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ChatErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ChatErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetChatAttachmentResponse parses an HTTP response from a GetChatAttachmentWithResponse call
func ParseGetChatAttachmentResponse(rsp *http.Response) (*GetChatAttachmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChatAttachmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListConversationsResponse parses an HTTP response from a ListConversationsWithResponse call
func ParseListConversationsResponse(rsp *http.Response) (*ListConversationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListConversationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ChatConversationDTO
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteConversationResponse parses an HTTP response from a DeleteConversationWithResponse call
func ParseDeleteConversationResponse(rsp *http.Response) (*DeleteConversationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteConversationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetConversationMessagesResponse parses an HTTP response from a GetConversationMessagesWithResponse call
func ParseGetConversationMessagesResponse(rsp *http.Response) (*GetConversationMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConversationMessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ChatMessageDTO
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ChatErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetMessageAudioResponse parses an HTTP response from a GetMessageAudioWithResponse call
func ParseGetMessageAudioResponse(rsp *http.Response) (*GetMessageAudioResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMessageAudioResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseVoteChatMessageResponse parses an HTTP response from a VoteChatMessageWithResponse call
func ParseVoteChatMessageResponse(rsp *http.Response) (*VoteChatMessageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VoteChatMessageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ChatErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ChatErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseSendChatMessageResponse parses an HTTP response from a SendChatMessageWithResponse call
func ParseSendChatMessageResponse(rsp *http.Response) (*SendChatMessageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendChatMessageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListTasksResponse parses an HTTP response from a ListTasksWithResponse call
func ParseListTasksResponse(rsp *http.Response) (*ListTasksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTasksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TaskTaskDTO
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateTaskResponse parses an HTTP response from a CreateTaskWithResponse call
func ParseCreateTaskResponse(rsp *http.Response) (*CreateTaskResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateTaskResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest TaskTaskDTO
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest TaskErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetTaskResponse parses an HTTP response from a GetTaskWithResponse call
func ParseGetTaskResponse(rsp *http.Response) (*GetTaskResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTaskResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TaskTaskDTO
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest TaskErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetTaskStepsResponse parses an HTTP response from a GetTaskStepsWithResponse call
func ParseGetTaskStepsResponse(rsp *http.Response) (*GetTaskStepsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTaskStepsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TaskStepDTO
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
