<?php
/**
 * GetUsageCurrentPeriodView
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lalternative\Spore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lalternative\Spore\Model;

use \ArrayAccess;
use \Lalternative\Spore\ObjectSerializer;

/**
 * GetUsageCurrentPeriodView Class Doc Comment
 *
 * @category Class
 * @package  Lalternative\Spore
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetUsageCurrentPeriodView implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'get_usage.CurrentPeriodView';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'by_identity' => '\Lalternative\Spore\Model\GetUsageIdentityBreakdown[]',
        'included_emails' => 'int',
        'limit' => 'int',
        'overage_cents' => 'int',
        'overage_emails' => 'int',
        'period_start' => 'string',
        'plan' => 'string',
        'sent_count' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'by_identity' => null,
        'included_emails' => null,
        'limit' => null,
        'overage_cents' => null,
        'overage_emails' => null,
        'period_start' => null,
        'plan' => null,
        'sent_count' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'by_identity' => false,
        'included_emails' => false,
        'limit' => false,
        'overage_cents' => false,
        'overage_emails' => false,
        'period_start' => false,
        'plan' => false,
        'sent_count' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'by_identity' => 'byIdentity',
        'included_emails' => 'includedEmails',
        'limit' => 'limit',
        'overage_cents' => 'overageCents',
        'overage_emails' => 'overageEmails',
        'period_start' => 'periodStart',
        'plan' => 'plan',
        'sent_count' => 'sentCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'by_identity' => 'setByIdentity',
        'included_emails' => 'setIncludedEmails',
        'limit' => 'setLimit',
        'overage_cents' => 'setOverageCents',
        'overage_emails' => 'setOverageEmails',
        'period_start' => 'setPeriodStart',
        'plan' => 'setPlan',
        'sent_count' => 'setSentCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'by_identity' => 'getByIdentity',
        'included_emails' => 'getIncludedEmails',
        'limit' => 'getLimit',
        'overage_cents' => 'getOverageCents',
        'overage_emails' => 'getOverageEmails',
        'period_start' => 'getPeriodStart',
        'plan' => 'getPlan',
        'sent_count' => 'getSentCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('by_identity', $data ?? [], null);
        $this->setIfExists('included_emails', $data ?? [], null);
        $this->setIfExists('limit', $data ?? [], null);
        $this->setIfExists('overage_cents', $data ?? [], null);
        $this->setIfExists('overage_emails', $data ?? [], null);
        $this->setIfExists('period_start', $data ?? [], null);
        $this->setIfExists('plan', $data ?? [], null);
        $this->setIfExists('sent_count', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets by_identity
     *
     * @return \Lalternative\Spore\Model\GetUsageIdentityBreakdown[]|null
     */
    public function getByIdentity()
    {
        return $this->container['by_identity'];
    }

    /**
     * Sets by_identity
     *
     * @param \Lalternative\Spore\Model\GetUsageIdentityBreakdown[]|null $by_identity by_identity
     *
     * @return self
     */
    public function setByIdentity($by_identity)
    {
        if (is_null($by_identity)) {
            throw new \InvalidArgumentException('non-nullable by_identity cannot be null');
        }
        $this->container['by_identity'] = $by_identity;

        return $this;
    }

    /**
     * Gets included_emails
     *
     * @return int|null
     */
    public function getIncludedEmails()
    {
        return $this->container['included_emails'];
    }

    /**
     * Sets included_emails
     *
     * @param int|null $included_emails IncludedEmails is what the subscription price buys. On a plan with no hard cap it is the only number that tells a tenant where billing starts, since Limit is -1 there.
     *
     * @return self
     */
    public function setIncludedEmails($included_emails)
    {
        if (is_null($included_emails)) {
            throw new \InvalidArgumentException('non-nullable included_emails cannot be null');
        }
        $this->container['included_emails'] = $included_emails;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return int|null
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param int|null $limit -1 means unlimited
     *
     * @return self
     */
    public function setLimit($limit)
    {
        if (is_null($limit)) {
            throw new \InvalidArgumentException('non-nullable limit cannot be null');
        }
        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets overage_cents
     *
     * @return int|null
     */
    public function getOverageCents()
    {
        return $this->container['overage_cents'];
    }

    /**
     * Sets overage_cents
     *
     * @param int|null $overage_cents overage_cents
     *
     * @return self
     */
    public function setOverageCents($overage_cents)
    {
        if (is_null($overage_cents)) {
            throw new \InvalidArgumentException('non-nullable overage_cents cannot be null');
        }
        $this->container['overage_cents'] = $overage_cents;

        return $this;
    }

    /**
     * Gets overage_emails
     *
     * @return int|null
     */
    public function getOverageEmails()
    {
        return $this->container['overage_emails'];
    }

    /**
     * Sets overage_emails
     *
     * @param int|null $overage_emails OverageEmails is how much of SentCount sits past IncludedEmails, and OverageCents what it would cost. Reported, not yet invoiced — see the note on Pro in plans/domain/catalog.go.
     *
     * @return self
     */
    public function setOverageEmails($overage_emails)
    {
        if (is_null($overage_emails)) {
            throw new \InvalidArgumentException('non-nullable overage_emails cannot be null');
        }
        $this->container['overage_emails'] = $overage_emails;

        return $this;
    }

    /**
     * Gets period_start
     *
     * @return string|null
     */
    public function getPeriodStart()
    {
        return $this->container['period_start'];
    }

    /**
     * Sets period_start
     *
     * @param string|null $period_start period_start
     *
     * @return self
     */
    public function setPeriodStart($period_start)
    {
        if (is_null($period_start)) {
            throw new \InvalidArgumentException('non-nullable period_start cannot be null');
        }
        $this->container['period_start'] = $period_start;

        return $this;
    }

    /**
     * Gets plan
     *
     * @return string|null
     */
    public function getPlan()
    {
        return $this->container['plan'];
    }

    /**
     * Sets plan
     *
     * @param string|null $plan plan
     *
     * @return self
     */
    public function setPlan($plan)
    {
        if (is_null($plan)) {
            throw new \InvalidArgumentException('non-nullable plan cannot be null');
        }
        $this->container['plan'] = $plan;

        return $this;
    }

    /**
     * Gets sent_count
     *
     * @return int|null
     */
    public function getSentCount()
    {
        return $this->container['sent_count'];
    }

    /**
     * Sets sent_count
     *
     * @param int|null $sent_count sent_count
     *
     * @return self
     */
    public function setSentCount($sent_count)
    {
        if (is_null($sent_count)) {
            throw new \InvalidArgumentException('non-nullable sent_count cannot be null');
        }
        $this->container['sent_count'] = $sent_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
