# coding: utf-8

"""
    Spore API

    Control plane for the Spore transactional email platform.

    The version of the OpenAPI document: 0.1.0
    Contact: contact@sporee.fr
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from spore_email.models.get_usage_identity_breakdown import GetUsageIdentityBreakdown
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetUsageCurrentPeriodView(BaseModel):
    """
    GetUsageCurrentPeriodView
    """ # noqa: E501
    by_identity: Optional[List[GetUsageIdentityBreakdown]] = Field(default=None, alias="byIdentity")
    included_emails: Optional[StrictInt] = Field(default=None, description="IncludedEmails is what the subscription price buys. On a plan with no hard cap it is the only number that tells a tenant where billing starts, since Limit is -1 there.", alias="includedEmails")
    limit: Optional[StrictInt] = Field(default=None, description="-1 means unlimited")
    overage_cents: Optional[StrictInt] = Field(default=None, alias="overageCents")
    overage_emails: Optional[StrictInt] = Field(default=None, description="OverageEmails is how much of SentCount sits past IncludedEmails, and OverageCents what it would cost. Reported, not yet invoiced — see the note on Pro in plans/domain/catalog.go.", alias="overageEmails")
    period_start: Optional[StrictStr] = Field(default=None, alias="periodStart")
    plan: Optional[StrictStr] = None
    sent_count: Optional[StrictInt] = Field(default=None, alias="sentCount")
    __properties: ClassVar[List[str]] = ["byIdentity", "includedEmails", "limit", "overageCents", "overageEmails", "periodStart", "plan", "sentCount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetUsageCurrentPeriodView from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in by_identity (list)
        _items = []
        if self.by_identity:
            for _item_by_identity in self.by_identity:
                if _item_by_identity:
                    _items.append(_item_by_identity.to_dict())
            _dict['byIdentity'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetUsageCurrentPeriodView from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "byIdentity": [GetUsageIdentityBreakdown.from_dict(_item) for _item in obj["byIdentity"]] if obj.get("byIdentity") is not None else None,
            "includedEmails": obj.get("includedEmails"),
            "limit": obj.get("limit"),
            "overageCents": obj.get("overageCents"),
            "overageEmails": obj.get("overageEmails"),
            "periodStart": obj.get("periodStart"),
            "plan": obj.get("plan"),
            "sentCount": obj.get("sentCount")
        })
        return _obj
