# coding: utf-8

"""
    Spore API

    Control plane for the Spore transactional email platform.

    The version of the OpenAPI document: 0.1.0
    Contact: contact@sporee.fr
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SetBrandSetBrandRequest(BaseModel):
    """
    SetBrandSetBrandRequest
    """ # noqa: E501
    app_name: Optional[StrictStr] = Field(default=None, alias="appName")
    font_family: Optional[StrictStr] = Field(default=None, alias="fontFamily")
    footer_text: Optional[StrictStr] = Field(default=None, alias="footerText")
    locale: Optional[StrictStr] = None
    logo_url: Optional[StrictStr] = Field(default=None, alias="logoUrl")
    primary_color: Optional[StrictStr] = Field(default=None, alias="primaryColor")
    support_email: Optional[StrictStr] = Field(default=None, alias="supportEmail")
    website_url: Optional[StrictStr] = Field(default=None, alias="websiteUrl")
    __properties: ClassVar[List[str]] = ["appName", "fontFamily", "footerText", "locale", "logoUrl", "primaryColor", "supportEmail", "websiteUrl"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SetBrandSetBrandRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SetBrandSetBrandRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "appName": obj.get("appName"),
            "fontFamily": obj.get("fontFamily"),
            "footerText": obj.get("footerText"),
            "locale": obj.get("locale"),
            "logoUrl": obj.get("logoUrl"),
            "primaryColor": obj.get("primaryColor"),
            "supportEmail": obj.get("supportEmail"),
            "websiteUrl": obj.get("websiteUrl")
        })
        return _obj
