/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`downgrade_billing_subscription`]
#[derive(Clone, Debug)]
pub struct DowngradeBillingSubscriptionParams {
    /// Target plan
    pub downgrade_subscription_downgrade_request: models::DowngradeSubscriptionDowngradeRequest
}

/// struct for passing parameters to the method [`quote_billing_upgrade`]
#[derive(Clone, Debug)]
pub struct QuoteBillingUpgradeParams {
    /// Target plan
    pub upgrade_subscription_quote_request: models::UpgradeSubscriptionQuoteRequest
}

/// struct for passing parameters to the method [`start_billing_checkout`]
#[derive(Clone, Debug)]
pub struct StartBillingCheckoutParams {
    /// Plan to subscribe to
    pub start_checkout_start_checkout_request: models::StartCheckoutStartCheckoutRequest
}

/// struct for passing parameters to the method [`upgrade_billing_subscription`]
#[derive(Clone, Debug)]
pub struct UpgradeBillingSubscriptionParams {
    /// Target plan and accepted amount
    pub upgrade_subscription_upgrade_request: models::UpgradeSubscriptionUpgradeRequest
}


/// struct for typed errors of method [`cancel_billing_pending_change`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CancelBillingPendingChangeError {
    Status401(models::EchoHttpError),
    Status404(models::EchoHttpError),
    Status503(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`cancel_billing_subscription`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CancelBillingSubscriptionError {
    Status401(models::EchoHttpError),
    Status404(models::EchoHttpError),
    Status503(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`downgrade_billing_subscription`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DowngradeBillingSubscriptionError {
    Status400(models::EchoHttpError),
    Status401(models::EchoHttpError),
    Status404(models::EchoHttpError),
    Status422(models::EchoHttpError),
    Status503(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_billing_state`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBillingStateError {
    Status401(models::EchoHttpError),
    Status500(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`lungor_webhook`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LungorWebhookError {
    Status401(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`quote_billing_upgrade`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuoteBillingUpgradeError {
    Status400(models::EchoHttpError),
    Status401(models::EchoHttpError),
    Status404(models::EchoHttpError),
    Status422(models::EchoHttpError),
    Status503(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`start_billing_checkout`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StartBillingCheckoutError {
    Status400(models::EchoHttpError),
    Status401(models::EchoHttpError),
    Status409(models::EchoHttpError),
    Status422(models::EchoHttpError),
    Status503(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`upgrade_billing_subscription`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpgradeBillingSubscriptionError {
    Status400(models::EchoHttpError),
    Status401(models::EchoHttpError),
    Status402(models::EchoHttpError),
    Status404(models::EchoHttpError),
    Status409(models::EchoHttpError),
    Status422(models::EchoHttpError),
    Status503(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}


/// Withdraws a scheduled downgrade before it fires. Idempotent: withdrawing when nothing is scheduled succeeds.
pub async fn cancel_billing_pending_change(configuration: &configuration::Configuration) -> Result<(), Error<CancelBillingPendingChangeError>> {

    let uri_str = format!("{}/billing/pending-change", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CancelBillingPendingChangeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Stops future charges. Access is NOT revoked: the period already paid for keeps entitling until it lapses, and the response carries that date. Idempotent.
pub async fn cancel_billing_subscription(configuration: &configuration::Configuration) -> Result<models::CancelSubscriptionResult, Error<CancelBillingSubscriptionError>> {

    let uri_str = format!("{}/billing/subscription", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CancelSubscriptionResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CancelSubscriptionResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CancelBillingSubscriptionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Schedules a move to a smaller tier, effective at the next renewal. Nothing changes today and nothing is refunded: the tenant keeps the tier they paid for until the current period ends. Moving to the free tier is a cancellation, not a downgrade.
pub async fn downgrade_billing_subscription(configuration: &configuration::Configuration, params: DowngradeBillingSubscriptionParams) -> Result<models::DowngradeSubscriptionResult, Error<DowngradeBillingSubscriptionError>> {

    let uri_str = format!("{}/billing/downgrade", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&params.downgrade_subscription_downgrade_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DowngradeSubscriptionResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DowngradeSubscriptionResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DowngradeBillingSubscriptionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns the subscription's health: which tier is paid for, whether a payment failed and until when it can still be fixed, and any scheduled change. A tenant who never subscribed is reported healthy with hasSubscription=false — the free tier is not a degraded state.
pub async fn get_billing_state(configuration: &configuration::Configuration) -> Result<models::GetBillingStateState, Error<GetBillingStateError>> {

    let uri_str = format!("{}/billing/state", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetBillingStateState`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetBillingStateState`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetBillingStateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Ingests Lungor's subscription lifecycle events. Authenticated by HMAC signature, not by API key — never called by clients.
pub async fn lungor_webhook(configuration: &configuration::Configuration) -> Result<String, Error<LungorWebhookError>> {

    let uri_str = format!("{}/billing/webhook/lungor", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LungorWebhookError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns the prorated amount owed today for moving to a larger tier — the difference between the tiers for the time remaining in the period already paid, never the catalogue price. Charges nothing. An amount of 0 means the upgrade is granted without a charge.
pub async fn quote_billing_upgrade(configuration: &configuration::Configuration, params: QuoteBillingUpgradeParams) -> Result<models::UpgradeSubscriptionQuote, Error<QuoteBillingUpgradeError>> {

    let uri_str = format!("{}/billing/upgrade/quote", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&params.upgrade_subscription_quote_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpgradeSubscriptionQuote`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpgradeSubscriptionQuote`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<QuoteBillingUpgradeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Opens a hosted payment that collects the first period and establishes the mandate future charges ride on. Returns the URL to redirect the customer to. Entitlement is granted only once the payment is confirmed by the provider webhook — this endpoint grants nothing.
pub async fn start_billing_checkout(configuration: &configuration::Configuration, params: StartBillingCheckoutParams) -> Result<models::StartCheckoutResult, Error<StartBillingCheckoutError>> {

    let uri_str = format!("{}/billing/checkout", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&params.start_checkout_start_checkout_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StartCheckoutResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StartCheckoutResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StartBillingCheckoutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Moves the tenant to a larger tier, effective immediately. The prorated difference is charged on the existing mandate BEFORE the tier is applied: a declined charge leaves the tier untouched. Requires explicit consent to the amount returned by the quote endpoint.
pub async fn upgrade_billing_subscription(configuration: &configuration::Configuration, params: UpgradeBillingSubscriptionParams) -> Result<models::UpgradeSubscriptionResult, Error<UpgradeBillingSubscriptionError>> {

    let uri_str = format!("{}/billing/upgrade", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&params.upgrade_subscription_upgrade_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpgradeSubscriptionResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpgradeSubscriptionResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpgradeBillingSubscriptionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}
