/*
 * Spore API
 *
 * Control plane for the Spore transactional email platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@sporee.fr
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`create_webhook_endpoint`]
#[derive(Clone, Debug)]
pub struct CreateWebhookEndpointParams {
    /// Endpoint to create
    pub create_endpoint_create_endpoint_request: models::CreateEndpointCreateEndpointRequest
}

/// struct for passing parameters to the method [`delete_webhook_endpoint`]
#[derive(Clone, Debug)]
pub struct DeleteWebhookEndpointParams {
    /// Endpoint ID
    pub id: String
}

/// struct for passing parameters to the method [`get_webhook_endpoint`]
#[derive(Clone, Debug)]
pub struct GetWebhookEndpointParams {
    /// Endpoint ID
    pub id: String
}

/// struct for passing parameters to the method [`list_webhook_endpoints`]
#[derive(Clone, Debug)]
pub struct ListWebhookEndpointsParams {
    /// Page size
    pub limit: Option<i32>,
    /// Offset
    pub offset: Option<i32>
}

/// struct for passing parameters to the method [`rotate_webhook_secret`]
#[derive(Clone, Debug)]
pub struct RotateWebhookSecretParams {
    /// Endpoint ID
    pub id: String
}

/// struct for passing parameters to the method [`update_webhook_endpoint`]
#[derive(Clone, Debug)]
pub struct UpdateWebhookEndpointParams {
    /// Endpoint ID
    pub id: String,
    /// Updated fields
    pub update_endpoint_update_endpoint_request: models::UpdateEndpointUpdateEndpointRequest
}


/// struct for typed errors of method [`create_webhook_endpoint`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateWebhookEndpointError {
    Status400(models::EchoHttpError),
    Status401(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_webhook_endpoint`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteWebhookEndpointError {
    Status400(models::EchoHttpError),
    Status401(models::EchoHttpError),
    Status404(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_webhook_endpoint`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetWebhookEndpointError {
    Status400(models::EchoHttpError),
    Status401(models::EchoHttpError),
    Status404(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_webhook_endpoints`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListWebhookEndpointsError {
    Status400(models::EchoHttpError),
    Status401(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rotate_webhook_secret`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RotateWebhookSecretError {
    Status400(models::EchoHttpError),
    Status401(models::EchoHttpError),
    Status404(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_webhook_endpoint`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateWebhookEndpointError {
    Status400(models::EchoHttpError),
    Status401(models::EchoHttpError),
    Status404(models::EchoHttpError),
    UnknownValue(serde_json::Value),
}


pub async fn create_webhook_endpoint(configuration: &configuration::Configuration, params: CreateWebhookEndpointParams) -> Result<models::CreateEndpointResult, Error<CreateWebhookEndpointError>> {

    let uri_str = format!("{}/webhooks/endpoints", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&params.create_endpoint_create_endpoint_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateEndpointResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateEndpointResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateWebhookEndpointError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_webhook_endpoint(configuration: &configuration::Configuration, params: DeleteWebhookEndpointParams) -> Result<(), Error<DeleteWebhookEndpointError>> {

    let uri_str = format!("{}/webhooks/endpoints/{id}", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteWebhookEndpointError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_webhook_endpoint(configuration: &configuration::Configuration, params: GetWebhookEndpointParams) -> Result<models::RepositoryEndpointView, Error<GetWebhookEndpointError>> {

    let uri_str = format!("{}/webhooks/endpoints/{id}", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RepositoryEndpointView`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RepositoryEndpointView`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetWebhookEndpointError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_webhook_endpoints(configuration: &configuration::Configuration, params: ListWebhookEndpointsParams) -> Result<models::ListEndpointsResult, Error<ListWebhookEndpointsError>> {

    let uri_str = format!("{}/webhooks/endpoints", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListEndpointsResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListEndpointsResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListWebhookEndpointsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn rotate_webhook_secret(configuration: &configuration::Configuration, params: RotateWebhookSecretParams) -> Result<models::RotateSecretResult, Error<RotateWebhookSecretError>> {

    let uri_str = format!("{}/webhooks/endpoints/{id}/rotate-secret", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RotateSecretResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RotateSecretResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RotateWebhookSecretError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_webhook_endpoint(configuration: &configuration::Configuration, params: UpdateWebhookEndpointParams) -> Result<(), Error<UpdateWebhookEndpointError>> {

    let uri_str = format!("{}/webhooks/endpoints/{id}", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&params.update_endpoint_update_endpoint_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateWebhookEndpointError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}
